TRAIN_DATA_PATH = r'C:\Users\danya\PycharmProjects\NBAGamesPredictor\Data\train_data\17-18_allgames.csv'
TRAIN_ALLSTAR_PATH = r'C:\Users\danya\PycharmProjects\NBAGamesPredictor\Data\auxilary_data\17-18_allstars.csv'
TRAIN_STANDINGS_PATH = r'C:\Users\danya\PycharmProjects\NBAGamesPredictor\Data\auxilary_data\16-17_standings.csv'
TEST_DATA_PATH = r'C:\Users\danya\PycharmProjects\NBAGamesPredictor\Data\test_data\18_19_allgames.csv'
TEST_ALLSTAR_PATH = r'C:\Users\danya\PycharmProjects\NBAGamesPredictor\Data\auxilary_data\18-19_allstars.csv'
TEST_STANDINGS_PATH = r'C:\Users\danya\PycharmProjects\NBAGamesPredictor\Data\auxilary_data\17-18_standings.csv'